DROP DATABASE IF EXISTS `CAFE`;
create DATABASE CAFE;
use CAFE;

DROP TABLE IF EXISTS `STAFF`;
DROP TABLE IF EXISTS `STAFF_ASSOCIATES`;
DROP TABLE IF EXISTS `CHEF`;
DROP TABLE IF EXISTS `WAITER`;
DROP TABLE IF EXISTS `SALARY`;
DROP TABLE IF EXISTS `MENU`;
DROP TABLE IF EXISTS `CUSTOMER`;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS `COMPLETE_INFO`;
DROP TABLE IF EXISTS `PAYMENT`;

CREATE TABLE `STAFF`(
	STAFF_ID BIGINT NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
	EMAIL VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(50),
	DOB DATE,
	CATEGORY VARCHAR(20) NOT NULL,
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `STAFF_CONTACT`(
	STAFF_ID BIGINT NOT NULL,
	CONTACT_NUMBER BIGINT NOT NULL,
	FOREIGN KEY(`STAFF_ID`) REFERENCES `STAFF`(`STAFF_ID`)
);

CREATE TABLE `STAFF_ASSOCIATES`(
	STAFF_ID BIGINT NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
	ADDRESS VARCHAR(50),
	CONTACT_NUMBER BIGINT NOT NULL,
	FOREIGN KEY(`STAFF_ID`) REFERENCES `STAFF`(`STAFF_ID`)	
);

CREATE TABLE `CHEF`(
	STAFF_ID BIGINT NOT NULL,
	WORK_EXPERIENCE BIGINT NOT NULL,
	PRIMARY KEY(`STAFF_ID`)
);

CREATE TABLE `WAITER`(
	STAFF_ID BIGINT NOT NULL,
	LANGUAGE VARCHAR(20) NOT NULL,
	PRIMARY KEY(`STAFF_ID`)
);

CREATE TABLE `SALARY`(
	STAFF_ID BIGINT NOT NULL,
	BASE_SALARY BIGINT NOT NULL,
	BONUS BIGINT NOT NULL,
	DEDUCTIONS BIGINT,
	PRIMARY KEY(`STAFF ID`)
);

CREATE TABLE `MENU`(
	FOOD_ID BIGINT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	ABOUT VARCHAR(50) NOT NULL,
	PRICE REAL NOT NULL,
	NO_OF_TIMES_ORDERED BIGINT NOT NULL,
	RATING REAL
);

CREATE TABLE `FOOD_CATEGORY`(
	FOOD_ID BIGINT NOT NULL,
	CATEGORY VARCHAR(20) NOT NULL,
	FOREIGN KEY(`FOOD_ID`) REFERENCES `MENU`(`FOOD_ID`),
);

CREATE TABLE `CUSTOMER`(
	CUSTOMER_ID BIGINT NOT NULL,
	FNAME VARCHAR(30) NOT NULL,
	LNAME VARCHAR(30),
	CONTACT_NUMBER BIGINT NOT NULL,
	PRIMARY KEY(`CUSTOMER_ID`)
);

CREATE TABLE `ORDER`(
	ORDER_ID BIGINT NOT NULL,
	INVOICE_ID BIGINT NOT NULL,
	FOOD_ID BIGINT NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	DISCOUNT BIGINT,
	QUANTITY BIGINT,
	RATING BIGINT,
	PRIMARY KEY(FOOD_ID,INVOICE_ID)
	FOREIGN KEY(`FOOD_ID`) REFERENCES `MENU`(`FOOD_ID`),
	FOREIGN KEY(`INVOICE_ID`) REFERENCES `COMPLETE_INFO`(`INVOICE_ID`),
);

CREATE TABLE `COMPLETE_INFO`(
	INVOICE_ID BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	TABLE_NUMBER BIGINT NOT NULL,
	TIME_OF_DAY TIME,
	TOTAL_AMOUNT REAL, NOT NULL,
	STATUS VARCHAR(20),
	PRIMARY KEY(`INVOICE_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
);

CREATE TABLE `PAYMENT`(
	PAYMENT_ID BIGINT NOT NULL,
	INVOICE_ID BIGINT NOT NULL,
	AMOUNT REAL NOT NULL,
	PORTAL VARCHAR(20),
	PRIMARY KEY(`PAYMENT_ID`),
	FOREIGN KEY(`INVOICE_ID`) REFERENCES `COMPLETE_INFO`(`INVOICE_ID`)
);

CREATE TABLE `SERVING`(
	STAFF_ID BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	FOREIGN KEY(`STAFF_ID`) REFERENCES `WAITER`(`STAFF_ID`),
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
);

CREATE TABLE `PREPARING`(
	STAFF_ID BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	FOREIGN KEY(`STAFF_ID`) REFERENCES `CHEF`(`STAFF_ID`),
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
);

CREATE TABLE `MANAGES`(
	MANAGER_ID BIGINT NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	FOREIGN KEY(`MANAGER_ID`) REFERENCES `STAFF`(`STAFF_ID`),
	FOREIGN KEY(`STAFF_ID`) REFERENCES `STAFF`(`STAFF_ID`),
);

CREATE TABLE `ORDERING`(
	CUSTOMER_ID BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
);

CREATE TABLE `GENERATING_EINVOICE`(
	CUSTOMER_ID BIGINT NOT NULL,
	INVOICE_ID BIGINT NOT NULL,
	PAYMENT_ID BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
	FOREIGN KEY(`INVOICE_ID`) REFERENCES `COMPLETE_INFO`(`INVOICE_ID`),
	FOREIGN KEY(`PAYMENT_ID`) REFERENCES `PAYMENT`(`PAYMENT_ID`),
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
);